#!/bin/bash - 
#===============================================================================
#
#          FILE: npost
# 
#         USAGE: ./npost
# 
#   DESCRIPTION: Create a new Post
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: YOUR NAME (), 
#  ORGANIZATION: 
#       CREATED: 02/13/2014 07:23
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

touch "`date +%F`.sh"
[[ -f "./header.sh" ]] && cat header.sh >> "`date +%F`.sh"
$EDITOR "`date +%F`.sh"
